In [1]:
import pandas as pd
from pathlib import Path

In [3]:
CICIDS_PATH = Path(
    r"D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017"
)

CIC_IOT_PATH = Path(
    r"D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CIC-IoT2023"
)

In [4]:
cicids_files = list(CICIDS_PATH.glob("*.csv"))

print("Number of CSV files:", len(cicids_files))

for file in cicids_files:
    print(file.name)

Number of CSV files: 8
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Friday-WorkingHours-Morning.pcap_ISCX.csv
Monday-WorkingHours.pcap_ISCX.csv
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Tuesday-WorkingHours.pcap_ISCX.csv
Wednesday-workingHours.pcap_ISCX.csv

In [5]:
dataset_summary = []

for file in cicids_files:
    df = pd.read_csv(file)

    dataset_summary.append({
        "File": file.name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Label_Column": df.columns[-1]
    })

cicids_summary = pd.DataFrame(dataset_summary)

cicids_summary

,File,Rows,Columns,Label_Column
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,225745,79,Label
1,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,286467,79,Label
2,Friday-WorkingHours-Morning.pcap_ISCX.csv,191033,79,Label
3,Monday-WorkingHours.pcap_ISCX.csv,529918,79,Label
4,Thursday-WorkingHours-Afternoon-Infilteration....,288602,79,Label
5,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,79,Label
6,Tuesday-WorkingHours.pcap_ISCX.csv,445909,79,Label
7,Wednesday-workingHours.pcap_ISCX.csv,692703,79,Label

In [7]:
iot_files = list(CIC_IOT_PATH.glob("*/*.csv"))

print("Number of CSV files:", len(iot_files))

for file in iot_files:
    print(file.name)

Number of CSV files: 309
Backdoor_Malware.pcap.csv
BenignTraffic.pcap.csv
BenignTraffic1.pcap.csv
BenignTraffic2.pcap.csv
BenignTraffic3.pcap.csv
BrowserHijacking.pcap.csv
CommandInjection.pcap.csv
DDoS-ACK_Fragmentation.pcap.csv
DDoS-ACK_Fragmentation1.pcap.csv
DDoS-ACK_Fragmentation10.pcap.csv
DDoS-ACK_Fragmentation11.pcap.csv
DDoS-ACK_Fragmentation12.pcap.csv
DDoS-ACK_Fragmentation2.pcap.csv
DDoS-ACK_Fragmentation3.pcap.csv
DDoS-ACK_Fragmentation4.pcap.csv
DDoS-ACK_Fragmentation5.pcap.csv
DDoS-ACK_Fragmentation6.pcap.csv
DDoS-ACK_Fragmentation7.pcap.csv
DDoS-ACK_Fragmentation8.pcap.csv
DDoS-ACK_Fragmentation9.pcap.csv
DDoS-HTTP_Flood-.pcap.csv
DDoS-ICMP_Flood.pcap.csv
DDoS-ICMP_Flood1.pcap.csv
DDoS-ICMP_Flood10.pcap.csv
DDoS-ICMP_Flood11.pcap.csv
DDoS-ICMP_Flood12.pcap.csv
DDoS-ICMP_Flood13.pcap.csv
DDoS-ICMP_Flood14.pcap.csv
DDoS-ICMP_Flood15.pcap.csv
DDoS-ICMP_Flood16.pcap.csv
DDoS-ICMP_Flood17.pcap.csv
DDoS-ICMP_Flood18.pcap.csv
DDoS-ICMP_Flood19.pcap.csv
DDoS-ICMP_Flood2.pcap.csv
DDoS-ICMP_Flood20.pcap.csv
DDoS-ICMP_Flood21.pcap.csv
DDoS-ICMP_Flood22.pcap.csv
DDoS-ICMP_Flood23.pcap.csv
DDoS-ICMP_Flood24.pcap.csv
DDoS-ICMP_Flood25.pcap.csv
DDoS-ICMP_Flood26.pcap.csv
DDoS-ICMP_Flood3.pcap.csv
DDoS-ICMP_Flood4.pcap.csv
DDoS-ICMP_Flood5.pcap.csv
DDoS-ICMP_Flood6.pcap.csv
DDoS-ICMP_Flood7.pcap.csv
DDoS-ICMP_Flood8.pcap.csv
DDoS-ICMP_Flood9.pcap.csv
DDoS-ICMP_Fragmentation.pcap.csv
DDoS-ICMP_Fragmentation1.pcap.csv
DDoS-ICMP_Fragmentation10.pcap.csv
DDoS-ICMP_Fragmentation11.pcap.csv
DDoS-ICMP_Fragmentation12.pcap.csv
DDoS-ICMP_Fragmentation13.pcap.csv
DDoS-ICMP_Fragmentation14.pcap.csv
DDoS-ICMP_Fragmentation15.pcap.csv
DDoS-ICMP_Fragmentation16.pcap.csv
DDoS-ICMP_Fragmentation17.pcap.csv
DDoS-ICMP_Fragmentation18.pcap.csv
DDoS-ICMP_Fragmentation19.pcap.csv
DDoS-ICMP_Fragmentation2.pcap.csv
DDoS-ICMP_Fragmentation3.pcap.csv
DDoS-ICMP_Fragmentation4.pcap.csv
DDoS-ICMP_Fragmentation5.pcap.csv
DDoS-ICMP_Fragmentation6.pcap.csv
DDoS-ICMP_Fragmentation7.pcap.csv
DDoS-ICMP_Fragmentation8.pcap.csv
DDoS-ICMP_Fragmentation9.pcap.csv
DDoS-PSHACK_Flood.pcap.csv
DDoS-PSHACK_Flood1.pcap.csv
DDoS-PSHACK_Flood10.pcap.csv
DDoS-PSHACK_Flood11.pcap.csv
DDoS-PSHACK_Flood12.pcap.csv
DDoS-PSHACK_Flood13.pcap.csv
DDoS-PSHACK_Flood14.pcap.csv
DDoS-PSHACK_Flood15.pcap.csv
DDoS-PSHACK_Flood2.pcap.csv
DDoS-PSHACK_Flood3.pcap.csv
DDoS-PSHACK_Flood4.pcap.csv
DDoS-PSHACK_Flood5.pcap.csv
DDoS-PSHACK_Flood6.pcap.csv
DDoS-PSHACK_Flood7.pcap.csv
DDoS-PSHACK_Flood8.pcap.csv
DDoS-PSHACK_Flood9.pcap.csv
DDoS-RSTFINFlood.pcap.csv
DDoS-RSTFINFlood1.pcap.csv
DDoS-RSTFINFlood10.pcap.csv
DDoS-RSTFINFlood11.pcap.csv
DDoS-RSTFINFlood12.pcap.csv
DDoS-RSTFINFlood13.pcap.csv
DDoS-RSTFINFlood14.pcap.csv
DDoS-RSTFINFlood15.pcap.csv
DDoS-RSTFINFlood2.pcap.csv
DDoS-RSTFINFlood3.pcap.csv
DDoS-RSTFINFlood4.pcap.csv
DDoS-RSTFINFlood5.pcap.csv
DDoS-RSTFINFlood6.pcap.csv
DDoS-RSTFINFlood7.pcap.csv
DDoS-RSTFINFlood8.pcap.csv
DDoS-RSTFINFlood9.pcap.csv
DDoS-SlowLoris.pcap.csv
DDoS-SynonymousIP_Flood.pcap.csv
DDoS-SynonymousIP_Flood1.pcap.csv
DDoS-SynonymousIP_Flood10.pcap.csv
DDoS-SynonymousIP_Flood11.pcap.csv
DDoS-SynonymousIP_Flood12.pcap.csv
DDoS-SynonymousIP_Flood13.pcap.csv
DDoS-SynonymousIP_Flood2.pcap.csv
DDoS-SynonymousIP_Flood3.pcap.csv
DDoS-SynonymousIP_Flood4.pcap.csv
DDoS-SynonymousIP_Flood5.pcap.csv
DDoS-SynonymousIP_Flood6.pcap.csv
DDoS-SynonymousIP_Flood7.pcap.csv
DDoS-SynonymousIP_Flood8.pcap.csv
DDoS-SynonymousIP_Flood9.pcap.csv
DDoS-SYN_Flood.pcap.csv
DDoS-SYN_Flood1.pcap.csv
DDoS-SYN_Flood10.pcap.csv
DDoS-SYN_Flood11.pcap.csv
DDoS-SYN_Flood12.pcap.csv
DDoS-SYN_Flood13.pcap.csv
DDoS-SYN_Flood14.pcap.csv
DDoS-SYN_Flood15.pcap.csv
DDoS-SYN_Flood2.pcap.csv
DDoS-SYN_Flood3.pcap.csv
DDoS-SYN_Flood4.pcap.csv
DDoS-SYN_Flood5.pcap.csv
DDoS-SYN_Flood6.pcap.csv
DDoS-SYN_Flood7.pcap.csv
DDoS-SYN_Flood8.pcap.csv
DDoS-SYN_Flood9.pcap.csv
DDoS-TCP_Flood.pcap.csv
DDoS-TCP_Flood1.pcap.csv
DDoS-TCP_Flood10.pcap.csv
DDoS-TCP_Flood11.pcap.csv
DDoS-TCP_Flood12.pcap.csv
DDoS-TCP_Flood13.pcap.csv
DDoS-TCP_Flood14.pcap.csv
DDoS-TCP_Flood15.pcap.csv
DDoS-TCP_Flood16.pcap.csv
DDoS-TCP_Flood17.pcap.csv
DDoS-TCP_Flood2.pcap.csv
DDoS-TCP_Flood3.pcap.csv
DDoS-TCP_Flood4.pcap.csv
DDoS-TCP_Flood5.pcap.csv
DDoS-TCP_Flood6.pcap.csv
DDoS-TCP_Flood7.pcap.csv
DDoS-TCP_Flood8.pcap.csv
DDoS-TCP_Flood9.pcap.csv
DDoS-UDP_Flood.pcap.csv
DDoS-UDP_Flood1.pcap.csv
DDoS-UDP_Flood10.pcap.csv
DDoS-UDP_Flood11.pcap.csv
DDoS-UDP_Flood12.pcap.csv
DDoS-UDP_Flood13.pcap.csv
DDoS-UDP_Flood14.pcap.csv
DDoS-UDP_Flood15.pcap.csv
DDoS-UDP_Flood16.pcap.csv
DDoS-UDP_Flood17.pcap.csv
DDoS-UDP_Flood18.pcap.csv
DDoS-UDP_Flood19.pcap.csv
DDoS-UDP_Flood2.pcap.csv
DDoS-UDP_Flood20.pcap.csv
DDoS-UDP_Flood3.pcap.csv
DDoS-UDP_Flood4.pcap.csv
DDoS-UDP_Flood5.pcap.csv
DDoS-UDP_Flood6.pcap.csv
DDoS-UDP_Flood7.pcap.csv
DDoS-UDP_Flood8.pcap.csv
DDoS-UDP_Flood9.pcap.csv
DDoS-UDP_Fragmentation.pcap.csv
DDoS-UDP_Fragmentation1.pcap.csv
DDoS-UDP_Fragmentation10.pcap.csv
DDoS-UDP_Fragmentation11.pcap.csv
DDoS-UDP_Fragmentation12.pcap.csv
DDoS-UDP_Fragmentation2.pcap.csv
DDoS-UDP_Fragmentation3.pcap.csv
DDoS-UDP_Fragmentation4.pcap.csv
DDoS-UDP_Fragmentation5.pcap.csv
DDoS-UDP_Fragmentation6.pcap.csv
DDoS-UDP_Fragmentation7.pcap.csv
DDoS-UDP_Fragmentation8.pcap.csv
DDoS-UDP_Fragmentation9.pcap.csv
DictionaryBruteForce.pcap.csv
DNS_Spoofing.pcap.csv
DoS-HTTP_Flood.pcap.csv
DoS-HTTP_Flood1.pcap.csv
DoS-SYN_Flood.pcap.csv
DoS-SYN_Flood1.pcap.csv
DoS-SYN_Flood2.pcap.csv
DoS-SYN_Flood3.pcap.csv
DoS-SYN_Flood4.pcap.csv
DoS-SYN_Flood5.pcap.csv
DoS-SYN_Flood6.pcap.csv
DoS-SYN_Flood7.pcap.csv
DoS-TCP_Flood.pcap.csv
DoS-TCP_Flood1.pcap.csv
DoS-TCP_Flood10.pcap.csv
DoS-TCP_Flood2.pcap.csv
DoS-TCP_Flood3.pcap.csv
DoS-TCP_Flood4.pcap.csv
DoS-TCP_Flood5.pcap.csv
DoS-TCP_Flood6.pcap.csv
DoS-TCP_Flood7.pcap.csv
DoS-TCP_Flood8.pcap.csv
DoS-TCP_Flood9.pcap.csv
DoS-UDP_Flood.pcap.csv
DoS-UDP_Flood1.pcap.csv
DoS-UDP_Flood10.pcap.csv
DoS-UDP_Flood11.pcap.csv
DoS-UDP_Flood12.pcap.csv
DoS-UDP_Flood13.pcap.csv
DoS-UDP_Flood14.pcap.csv
DoS-UDP_Flood15.pcap.csv
DoS-UDP_Flood16.pcap.csv
DoS-UDP_Flood2.pcap.csv
DoS-UDP_Flood3.pcap.csv
DoS-UDP_Flood4.pcap.csv
DoS-UDP_Flood5.pcap.csv
DoS-UDP_Flood6.pcap.csv
DoS-UDP_Flood7.pcap.csv
DoS-UDP_Flood8.pcap.csv
DoS-UDP_Flood9.pcap.csv
Mirai-greeth_flood.pcap.csv
Mirai-greeth_flood1.pcap.csv
Mirai-greeth_flood10.pcap.csv
Mirai-greeth_flood11.pcap.csv
Mirai-greeth_flood12.pcap.csv
Mirai-greeth_flood13.pcap.csv
Mirai-greeth_flood14.pcap.csv
Mirai-greeth_flood15.pcap.csv
Mirai-greeth_flood16.pcap.csv
Mirai-greeth_flood17.pcap.csv
Mirai-greeth_flood18.pcap.csv
Mirai-greeth_flood19.pcap.csv
Mirai-greeth_flood2.pcap.csv
Mirai-greeth_flood20.pcap.csv
Mirai-greeth_flood21.pcap.csv
Mirai-greeth_flood22.pcap.csv
Mirai-greeth_flood23.pcap.csv
Mirai-greeth_flood24.pcap.csv
Mirai-greeth_flood25.pcap.csv
Mirai-greeth_flood26.pcap.csv
Mirai-greeth_flood27.pcap.csv
Mirai-greeth_flood28.pcap.csv
Mirai-greeth_flood3.pcap.csv
Mirai-greeth_flood4.pcap.csv
Mirai-greeth_flood5.pcap.csv
Mirai-greeth_flood6.pcap.csv
Mirai-greeth_flood7.pcap.csv
Mirai-greeth_flood8.pcap.csv
Mirai-greeth_flood9.pcap.csv
Mirai-greip_flood.pcap.csv
Mirai-greip_flood1.pcap.csv
Mirai-greip_flood10.pcap.csv
Mirai-greip_flood11.pcap.csv
Mirai-greip_flood12.pcap.csv
Mirai-greip_flood13.pcap.csv
Mirai-greip_flood14.pcap.csv
Mirai-greip_flood15.pcap.csv
Mirai-greip_flood16.pcap.csv
Mirai-greip_flood17.pcap.csv
Mirai-greip_flood18.pcap.csv
Mirai-greip_flood19.pcap.csv
Mirai-greip_flood2.pcap.csv
Mirai-greip_flood20.pcap.csv
Mirai-greip_flood21.pcap.csv
Mirai-greip_flood3.pcap.csv
Mirai-greip_flood4.pcap.csv
Mirai-greip_flood5.pcap.csv
Mirai-greip_flood6.pcap.csv
Mirai-greip_flood7.pcap.csv
Mirai-greip_flood8.pcap.csv
Mirai-greip_flood9.pcap.csv
Mirai-udpplain.pcap.csv
Mirai-udpplain1.pcap.csv
Mirai-udpplain10.pcap.csv
Mirai-udpplain11.pcap.csv
Mirai-udpplain12.pcap.csv
Mirai-udpplain13.pcap.csv
Mirai-udpplain14.pcap.csv
Mirai-udpplain15.pcap.csv
Mirai-udpplain16.pcap.csv
Mirai-udpplain17.pcap.csv
Mirai-udpplain18.pcap.csv
Mirai-udpplain19.pcap.csv
Mirai-udpplain2.pcap.csv
Mirai-udpplain20.pcap.csv
Mirai-udpplain21.pcap.csv
Mirai-udpplain22.pcap.csv
Mirai-udpplain23.pcap.csv
Mirai-udpplain24.pcap.csv
Mirai-udpplain3.pcap.csv
Mirai-udpplain4.pcap.csv
Mirai-udpplain5.pcap.csv
Mirai-udpplain6.pcap.csv
Mirai-udpplain7.pcap.csv
Mirai-udpplain8.pcap.csv
Mirai-udpplain9.pcap.csv
MITM-ArpSpoofing.pcap.csv
MITM-ArpSpoofing1.pcap.csv
Recon-HostDiscovery.pcap.csv
Recon-OSScan.pcap.csv
Recon-PingSweep.pcap.csv
Recon-PortScan.pcap.csv
SqlInjection.pcap.csv
Uploading_Attack.pcap.csv
VulnerabilityScan.pcap.csv
XSS.pcap.csv

In [8]:
iot_summary = []

for file in iot_files:
    df = pd.read_csv(file)

    iot_summary.append({
        "File": file.name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Label_Column": df.columns[-1]
    })

iot_summary = pd.DataFrame(iot_summary)

iot_summary

                           File    Rows  Columns Label_Column
0     Backdoor_Malware.pcap.csv    3218       39     Variance
1        BenignTraffic.pcap.csv  362361       39     Variance
2       BenignTraffic1.pcap.csv  295585       39     Variance
3       BenignTraffic2.pcap.csv  310413       39     Variance
4       BenignTraffic3.pcap.csv  129832       39     Variance
..                          ...     ...      ...          ...
304     Recon-PortScan.pcap.csv   82284       39     Variance
305       SqlInjection.pcap.csv    5245       39     Variance
306   Uploading_Attack.pcap.csv    1252       39     Variance
307  VulnerabilityScan.pcap.csv  373351       39     Variance
308                XSS.pcap.csv    3846       39     Variance

[309 rows x 4 columns]

In [9]:
sample_cicids = pd.read_csv(cicids_files[0])

print(sample_cicids.shape)
print(sample_cicids.columns.tolist())
sample_cicids.head()

(225745, 79)
[' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [10]:
sample_iot = pd.read_csv(iot_files[0])

print(sample_iot.shape)
print(sample_iot.columns.tolist())
sample_iot.head()

(3218, 39)
['Header_Length', 'Protocol Type', 'Time_To_Live', 'Rate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Variance']

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,13.2,17,111.8,21.654112,0.0,0.0,0.0,0.0,0.3,0.0,...,0.9,2105,60,1392,210.5,415.549502,210.5,0.046181,10,172681.388889
1,11.2,17,63.5,134.621809,0.0,0.1,0.0,0.0,0.0,0.0,...,1.0,4736,60,1392,473.6,632.696206,473.6,0.008186,10,400304.488889
2,13.6,17,65.6,211.662495,0.0,0.1,0.0,0.0,0.2,0.0,...,1.0,3788,62,1392,378.8,508.763381,378.8,0.004735,10,258840.177778
3,24.8,6,84.4,155.707333,0.0,0.0,0.0,0.4,0.7,0.0,...,1.0,2917,62,833,291.7,308.737951,291.7,0.006422,10,95319.122222
4,10.4,17,118.3,105.440687,0.0,0.0,0.0,0.0,0.1,0.0,...,1.0,1163,62,230,116.3,75.052648,116.3,0.009484,10,5632.900000

In [11]:
sample_cicids.dtypes

 Destination Port                int64
 Flow Duration                   int64
 Total Fwd Packets               int64
 Total Backward Packets          int64
Total Length of Fwd Packets      int64
                                ...
Idle Mean                      float64
 Idle Std                      float64
 Idle Max                        int64
 Idle Min                        int64
 Label                          object
Length: 79, dtype: object

In [12]:
sample_iot.dtypes

Header_Length      float64
Protocol Type        int64
Time_To_Live       float64
Rate               float64
fin_flag_number    float64
syn_flag_number    float64
rst_flag_number    float64
psh_flag_number    float64
ack_flag_number    float64
ece_flag_number    float64
cwr_flag_number    float64
ack_count            int64
syn_count            int64
fin_count            int64
rst_count            int64
HTTP               float64
HTTPS              float64
DNS                float64
Telnet             float64
SMTP               float64
SSH                float64
IRC                float64
TCP                float64
UDP                float64
DHCP               float64
ARP                float64
ICMP               float64
IGMP               float64
IPv                float64
LLC                float64
Tot sum              int64
Min                  int64
Max                  int64
AVG                float64
Std                float64
Tot size           float64
IAT                float64
Number               int64
Variance           float64
dtype: object

In [13]:
missing_cicids = sample_cicids.isnull().sum()

missing_cicids[missing_cicids > 0]

Flow Bytes/s    4
dtype: int64

In [14]:
missing_iot = sample_iot.isnull().sum()

missing_iot[missing_iot > 0]

Series([], dtype: int64)

In [15]:
sample_cicids.iloc[:, -1].value_counts()

 Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

In [16]:
sample_iot.iloc[:, -1].value_counts()

Variance
0.000000         227
203918.400000     12
475809.600000      7
52272.900000       7
3.600000           6
                ...
24417.877778       1
4231.822222        1
5323.388889        1
4142.266667        1
2778.696429        1
Name: count, Length: 2901, dtype: int64

In [17]:
sample_cicids.columns.tolist()

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 ' Label']

In [18]:
sample_iot.columns.tolist()

['Header_Length',
 'Protocol Type',
 'Time_To_Live',
 'Rate',
 'fin_flag_number',
 'syn_flag_number',
 'rst_flag_number',
 'psh_flag_number',
 'ack_flag_number',
 'ece_flag_number',
 'cwr_flag_number',
 'ack_count',
 'syn_count',
 'fin_count',
 'rst_count',
 'HTTP',
 'HTTPS',
 'DNS',
 'Telnet',
 'SMTP',
 'SSH',
 'IRC',
 'TCP',
 'UDP',
 'DHCP',
 'ARP',
 'ICMP',
 'IGMP',
 'IPv',
 'LLC',
 'Tot sum',
 'Min',
 'Max',
 'AVG',
 'Std',
 'Tot size',
 'IAT',
 'Number',
 'Variance']